version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: voting-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting_db
    ports:
      - "3307:3306"  # Expose MySQL on port 3307 on host, but MySQL still runs on 3306 inside the container
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - voting-network

  service-discovery:
    image: 2017445/service-discovery:latest  # Added :latest tag
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    container_name: service-discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - voting-network

  api-gateway:
    image: 2017445/api-gateway:latest  # Added :latest tag
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-discovery
      - mysql
    networks:
      - voting-network
    restart: always

  user-service:
    image: 2017445/user-service:latest  # Added :latest tag
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-discovery
      - mysql
    networks:
      - voting-network
    restart: always

  voting-service:
    image: 2017445/voting-service:latest  # Added :latest tag
    build:
      context: ./voting-service
      dockerfile: Dockerfile
    container_name: voting-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-discovery
      - mysql
      - user-service
    networks:
      - voting-network
    restart: always

volumes:
  mysql_data:

networks:
  voting-network:
    driver: bridge