# k8s/secrets/db-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  # "root" encoded in base64
  password: cm9vdA==
  database: dm90aW5nX2Ri  # "voting_db" encoded in base64