apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  secret: dTZacjdXWTlWdjV0RnNOLzF4YXA5aHltZkc5QThLKzFFZlc0akYyWmVpWT0=  # Your JWT secret encoded in base64
  expiration: ODY0MDAwMDA=