apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application.yaml: |
    server:
      port: 8081

    spring:
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/login, /register, /logout, /api/auth/**
              filters:
                - RewritePath=/(?<segment>.*), /$\{segment}
            - id: user-service-api
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
            - id: voting-service
              uri: lb://voting-service
              predicates:
                - Path=/api/voting/**, /voting/**
              filters:
                - StripPrefix=0
                - CustomTokenRequestFilter
      application:
        name: api-gateway

    eureka:
      instance:
        prefer-ip-address: true
      client:
        service-url:
          defaultZone: http://service-discovery:8761/eureka/
        fetch-registry: true
        register-with-eureka: true

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: always
      health:
        defaults:
          enabled: true