apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: 2017445/service-discovery:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/app/config/application.yaml
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: service-discovery-config